//===- BrilPasses.td - Bril dialect passes -------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef BRIL_PASS
#define BRIL_PASS

include "mlir/Pass/PassBase.td"

#endif // BRIL_PASS
